/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const AuthLayout: typeof import('./components/bussiness/AuthLayout/index').default
  const CodeBlockModal: typeof import('./components/common/Editor/src/TiptapEditor/modals').CodeBlockModal
  const CodeEditor: typeof import('./components/common/Editor/src/CodeEditor').default
  const CustomCodeBlockLowlight: typeof import('./components/common/Editor/src/TiptapEditor/extensions').CustomCodeBlockLowlight
  const CustomIframe: typeof import('./components/common/Editor/src/TiptapEditor/nodes').CustomIframe
  const CustomVideo: typeof import('./components/common/Editor/src/TiptapEditor/nodes').CustomVideo
  const Editor: typeof import('./components/common/Editor/src/Editor').default
  const EditorType: typeof import('./components/common/Editor/types').EditorType
  const Fragment: typeof import('react').Fragment
  const IframeModal: typeof import('./components/common/Editor/src/TiptapEditor/modals').IframeModal
  const JsonEditor: typeof import('./components/common/Editor/src/JsonEditor').default
  const Link: typeof import('react-router-dom').Link
  const LinkModal: typeof import('./components/common/Editor/src/TiptapEditor/LinkModal').LinkModal
  const Loading: typeof import('./components/common/Loading/index').default
  const MarkdownEditor: typeof import('./components/common/Editor/src/MarkdownEditor').default
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const PageContainer: typeof import('./components/common/PageContainer/index').default
  const PlainTextEditor: typeof import('./components/common/Editor/src/PlainTextEditor').default
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const SloganIcon: typeof import('./components/bussiness/AuthLayout/icons/SloganIcon').default
  const StatusBar: typeof import('./components/common/Editor/src/TiptapEditor/StatusBar').StatusBar
  const Suspense: typeof import('react').Suspense
  const ThemeLoading: typeof import('./components/common/Loading/index').ThemeLoading
  const TiptapEditor: typeof import('./components/common/Editor/src/TiptapEditor').default
  const Toolbar: typeof import('./components/common/Editor/src/TiptapEditor/Toolbar').Toolbar
  const VideoModal: typeof import('./components/common/Editor/src/TiptapEditor/modals').VideoModal
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const fetchAllDictEntries: typeof import('./hooks/useDictCache').fetchAllDictEntries
  const forwardRef: typeof import('react').forwardRef
  const getDictEntriesByTypeCode: typeof import('./hooks/useDictCache').getDictEntriesByTypeCode
  const getDictEntriesOptionsByTypeCode: typeof import('./hooks/useDictCache').getDictEntriesOptionsByTypeCode
  const getDictEntryLabel: typeof import('./hooks/useDictCache').getDictEntryLabel
  const getDictEntryLabelByValue: typeof import('./hooks/useDictCache').getDictEntryLabelByValue
  const getDictTypes: typeof import('./hooks/useDictCache').getDictTypes
  const initMonacoWorkers: typeof import('./components/common/Editor/src/monaco-loader').initMonacoWorkers
  const isDarkMode: typeof import('./components/common/Editor/src/utils').isDarkMode
  const languages: typeof import('./components/common/Editor/src/TiptapEditor/constants').languages
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const monacoLoader: typeof import('./components/common/Editor/src/monaco-loader').default
  const resetDictCache: typeof import('./hooks/useDictCache').resetDictCache
  const startRefreshTimer: typeof import('./hooks/useTokenRefresh').startRefreshTimer
  const startTransition: typeof import('react').startTransition
  const stopRefreshTimer: typeof import('./hooks/useTokenRefresh').stopRefreshTimer
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAuth: typeof import('./hooks/useAuth').useAuth
  const useAuthStore: typeof import('./stores/auth').useAuthStore
  const useAutoTableHeight: typeof import('./hooks/useTableScrollHeight').useAutoTableHeight
  const useCallback: typeof import('react').useCallback
  const useClipboard: typeof import('./hooks/useClipboard').useClipboard
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEcharts: typeof import('./hooks/useEcharts').useEcharts
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useKeyStroke: typeof import('./hooks/useKeyStroke').useKeyStroke
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const usePageRefreshStore: typeof import('./stores/pageRefresh').usePageRefreshStore
  const useParams: typeof import('react-router-dom').useParams
  const useProTableScrollY: typeof import('./hooks/useProTableScrollY').useProTableScrollY
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTableScrollHeight: typeof import('./hooks/useTableScrollHeight').useTableScrollHeight
  const useTabsStore: typeof import('./stores/tabs').useTabsStore
  const useTimes: typeof import('./hooks/useTime').useTimes
  const useTiptapEditor: typeof import('./components/common/Editor/src/TiptapEditor/useTiptapEditor').useTiptapEditor
  const useTitle: typeof import('./hooks/useTitle').useTitle
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
  const useUserStore: typeof import('./stores/user').useUserStore
  const useWatermark: typeof import('./hooks/useWatermark').useWatermark
}
// for type re-export
declare global {
  // @ts-ignore
  export type { DictEntry, DictType } from './hooks/useDictCache'
  import('./hooks/useDictCache')
  // @ts-ignore
  export type { ECOption } from './hooks/useEcharts'
  import('./hooks/useEcharts')
  // @ts-ignore
  export type { AuthLayoutProps } from './components/bussiness/AuthLayout/index'
  import('./components/bussiness/AuthLayout/index')
  // @ts-ignore
  export type { CodeEditorProps } from './components/common/Editor/src/CodeEditor'
  import('./components/common/Editor/src/CodeEditor')
  // @ts-ignore
  export type { JsonEditorProps } from './components/common/Editor/src/JsonEditor'
  import('./components/common/Editor/src/JsonEditor')
  // @ts-ignore
  export type { MarkdownEditorProps } from './components/common/Editor/src/MarkdownEditor'
  import('./components/common/Editor/src/MarkdownEditor')
  // @ts-ignore
  export type { PlainTextEditorProps } from './components/common/Editor/src/PlainTextEditor'
  import('./components/common/Editor/src/PlainTextEditor')
  // @ts-ignore
  export type { TiptapEditorProps } from './components/common/Editor/src/TiptapEditor'
  import('./components/common/Editor/src/TiptapEditor')
  // @ts-ignore
  export type { CodeBlockModalProps, VideoModalProps, IframeModalProps } from './components/common/Editor/src/TiptapEditor/modals'
  import('./components/common/Editor/src/TiptapEditor/modals')
  // @ts-ignore
  export type { EditorProps } from './components/common/Editor/types'
  import('./components/common/Editor/types')
  // @ts-ignore
  export type { ThemeLoadingProps } from './components/common/Loading/index'
  import('./components/common/Loading/index')
  // @ts-ignore
  export type { LoginOptions, AuthState } from './stores/auth'
  import('./stores/auth')
  // @ts-ignore
  export type { UserState } from './stores/user'
  import('./stores/user')
  // @ts-ignore
  export type { TabItem } from './stores/tabs'
  import('./stores/tabs')
}
